dist: bionic
language: python

matrix:
  include:
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=black
    - python: 3.8
      env: TOXENV=py38

    - python: 3.7
      env: TOXENV=py37

    - python: 3.6
      env: TOXENV=py36


install: 
  - sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - pip install tox
  - $TRAVIS_BUILD_DIR/scripts/travis.sh
before_script: sudo systemctl start clamav-daemon 
script: tox
